# Generated by Django 5.2.7 on 2025-11-01 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del administrador')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del administrador')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo del administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Casoclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Nombre del caso clínico')),
                ('resumen', models.CharField(max_length=300, verbose_name='Resumen del caso clínico')),
                ('estado', models.CharField(max_length=300, verbose_name='Estado del caso')),
            ],
        ),
        migrations.CreateModel(
            name='contenidomultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300, verbose_name='Tipo de contenido')),
                ('url_contenido', models.URLField()),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hipotesis', models.CharField(max_length=300, verbose_name='Posible diagnostico o idea inicial sobre el caso')),
                ('justificacion', models.CharField(max_length=300, verbose_name='Justificación del diagnóstico')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de envío del diagnóstico')),
                ('estado', models.CharField(max_length=150, verbose_name='Estado del diagnóstico')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del estudiante')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del estudiante')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo del estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(max_length=100, verbose_name='Calificación')),
                ('retroalimentacion', models.CharField(verbose_name='Retroalimentación')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de la evaluación')),
            ],
        ),
        migrations.CreateModel(
            name='Examenfisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('fecha_examen', models.DateField(verbose_name='Fecha del examen físico')),
                ('hallazgos', models.CharField(max_length=300, verbose_name='Hallazgos en el examen físico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del paciente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del paciente')),
                ('correo', models.CharField(max_length=200, verbose_name='Correo del paciente')),
            ],
        ),
        migrations.CreateModel(
            name='plantratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=300, verbose_name='Objetivo del plan de tratamiento')),
                ('detalle', models.CharField(max_length=300, verbose_name='Detalle del plan')),
                ('fecha_envio', models.DateField(verbose_name='Fecha de envío del plan de tratamiento')),
                ('estado', models.CharField(max_length=300, verbose_name='Estado del plan de tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del reporte')),
                ('fecha_generacion', models.DateField(verbose_name='Fecha de generación del reporte')),
                ('contenido_extraido', models.CharField(verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio de la simulación')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de término de la simulación')),
                ('motivo_consulta', models.CharField(max_length=300, verbose_name='Motivo de la consulta')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
            ],
        ),
    ]
