# Generated by Django 5.2.7 on 2025-11-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulacion',
            old_name='id_estudiante',
            new_name='nombre_estudiante',
        ),
        migrations.AddField(
            model_name='simulacion',
            name='nombre',
            field=models.CharField(default='exit', max_length=300, verbose_name='Nombre de la simulación'),
            preserve_default=False,
        ),
    ]
