# Generated by Django 5.2.7 on 2025-11-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_delete_administrador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Casoclinico',
            new_name='Caso_clinico',
        ),
        migrations.RenameModel(
            old_name='contenidomultimedia',
            new_name='Contenido_multimedia',
        ),
        migrations.RenameModel(
            old_name='Examenfisico',
            new_name='Examen_fisico',
        ),
        migrations.RenameModel(
            old_name='plantratamiento',
            new_name='Plan_de_tratamiento',
        ),
    ]
