# Generated by Django 5.2.7 on 2025-11-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_casoclinico_caso_clinico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=300, verbose_name='Tipo de contenido')),
                ('url_contenido', models.URLField(verbose_name='URL del contenido')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Contenido multimedia',
                'verbose_name_plural': 'Contenidos multimedia',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField(verbose_name='Calificación')),
                ('retroalimentacion', models.CharField(max_length=500, verbose_name='Retroalimentación')),
                ('fecha_evaluacion', models.DateField(verbose_name='Fecha de la evaluación')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.RenameModel(
            old_name='Caso_clinico',
            new_name='CasoClinico',
        ),
        migrations.RenameModel(
            old_name='Examen_fisico',
            new_name='ExamenFisico',
        ),
        migrations.RenameModel(
            old_name='Plan_de_tratamiento',
            new_name='PlanDeTratamiento',
        ),
        migrations.DeleteModel(
            name='Contenido_multimedia',
        ),
        migrations.DeleteModel(
            name='Evaluaciones',
        ),
        migrations.AlterModelOptions(
            name='casoclinico',
            options={'verbose_name': 'Caso clínico', 'verbose_name_plural': 'Casos clínicos'},
        ),
        migrations.AlterModelOptions(
            name='diagnostico',
            options={'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='examenfisico',
            options={'verbose_name': 'Examen físico', 'verbose_name_plural': 'Exámenes físicos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='plandetratamiento',
            options={'verbose_name': 'Plan de tratamiento', 'verbose_name_plural': 'Planes de tratamiento'},
        ),
        migrations.AlterModelOptions(
            name='reporte',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='simulacion',
            options={'verbose_name': 'Simulación', 'verbose_name_plural': 'Simulaciones'},
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='hipotesis',
            field=models.CharField(max_length=300, verbose_name='Posible diagnóstico o idea inicial sobre el caso'),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='contenido_extraido',
            field=models.TextField(verbose_name='Contenido'),
        ),
    ]
