# Generated by Django 5.2.7 on 2025-12-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('alumno', 'Alumno'), ('teacher', 'Docente'), ('admin', 'Administrador')], default='alumno', max_length=20),
        ),
    ]
