# Generated by Django 5.2.7 on 2025-11-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name_plural': 'Administradores'},
        ),
    ]
