# Generated by Django 5.2.8 on 2025-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre_emergencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre contacto de emergencia'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono contacto de emergencia'),
        ),
    ]
