# Generated by Django 5.2.8 on 2025-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondeusuarios', '0003_user_direccion_user_nombre_emergencia_user_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
    ]
