# Generated by Django 5.2.7 on 2025-11-21 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='cursos_dictados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examen',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='cursos.contenido'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='cursos.contenido'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='examen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulario', to='cursos.examen'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='cursos.formulario'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='usuario',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modulo',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='contenido',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='cursos.modulo'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cursos.formulario'),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cursos.pregunta'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='cursos.evaluacion'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='opcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.opcionrespuesta'),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.pregunta'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='modulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulacion', to='cursos.modulo'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='simulacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulario', to='cursos.simulacion'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('usuario', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='respuestaalumno',
            unique_together={('evaluacion', 'pregunta')},
        ),
    ]
