# Generated by Django 5.2.7 on 2025-11-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='contenidos/'),
        ),
    ]
