# Generated by Django 5.2.8 on 2025-11-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_contenido_archivo'),
        ('cursos', '0002_initial'),
    ]

    operations = [
    ]
