# Generated by Django 5.2.7 on 2025-11-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_merge_0002_contenido_archivo_0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={},
        ),
        migrations.AddField(
            model_name='modulo',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
