# Generated by Django 5.2.8 on 2025-11-27 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_modulo_options_modulo_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('seleccion', 'Selección múltiple'), ('abierta', 'Pregunta abierta')], default='seleccion', max_length=20),
        ),
        migrations.AddField(
            model_name='respuestaalumno',
            name='respuesta_texto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuestaalumno',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.opcionrespuesta'),
        ),
    ]
