# Generated by Django 5.2.8 on 2025-11-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_progresomodulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_esperada',
            field=models.TextField(blank=True, help_text='Sol se usa si la pregunta es abierta.'),
        ),
    ]
