# Generated by Django 5.2.8 on 2025-12-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_pregunta_respuesta_esperada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta_esperada',
            field=models.TextField(blank=True, help_text='Solo se usa si la pregunta es abierta.'),
        ),
    ]
