# Generated by Django 5.2.8 on 2025-12-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_progresosimulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacion',
            name='contenido_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='simulaciones/imagenes/'),
        ),
        migrations.AddField(
            model_name='simulacion',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='simulaciones/videos/'),
        ),
        migrations.AlterField(
            model_name='simulacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
