# Generated by Django 5.2.7 on 2025-11-01 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_delete_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del administrador')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido del administrador')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo del administrador')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.estudiante')),
            ],
        ),
    ]
