# Generated by Django 5.2.7 on 2025-11-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_id_estudiante_simulacion_nombre_estudiante_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
