# Generated by Django 5.2.8 on 2025-12-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fecha_actualizacion',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_REVISION', 'En revisión'), ('EN_PROGRESO', 'En progreso'), ('RESUELTO', 'Resuelto')], default='RECIBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
